from functools import wraps

from cryptography.fernet import Fernet, InvalidToken
from flask import abort, current_app
from flask_login import current_user


def roles_required(*roles):
    def decorator(view):
        @wraps(view)
        def wrapped(*args, **kwargs):
            if not current_user.is_authenticated or current_user.role not in roles:
                abort(403)
            return view(*args, **kwargs)
        return wrapped
    return decorator


def _fernet():
    key = current_app.config.get("CREDENTIAL_ENCRYPTION_KEY")
    if not key:
        raise RuntimeError(
            "FLASK_CREDENTIAL_ENCRYPTION_KEY is not configured. "
            "Run 'flask --app run.py generate-encryption-key' and put the result in .env."
        )
    try:
        return Fernet(key.encode() if isinstance(key, str) else key)
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            "FLASK_CREDENTIAL_ENCRYPTION_KEY is invalid. It must be exactly the value "
            "generated by 'flask --app run.py generate-encryption-key', without an extra prefix."
        ) from exc


def encrypt_secret(value):
    return _fernet().encrypt(value.encode()).decode()


def decrypt_secret(value):
    try:
        return _fernet().decrypt(value.encode()).decode()
    except InvalidToken as exc:
        raise RuntimeError("Unable to decrypt database credential") from exc
